v1.0.1

diff --git a/bump b/bump
--- a/bump
+++ b/bump
@@ -2,8 +2,8 @@
 
 
 if [[ $# == 0 ]]; then
-    echo "usage: bump [patch|minor|major|init|x.x.x] [current version]"
-    echo ""
+    echo "usage: bump [patch|minor|major x.x.x] or [init|x.x.x]"
+    echo "version: 1.0.1"
     exit 1
 fi
 
@@ -13,11 +13,18 @@ function join { local IFS="$1"; shift; echo "$*"; }
 
 
 NEXT=$1
-VERSION=$1
 
-if [[ $# > 1 ]]; then
+if [[ "$NEXT" == "patch" || "$NEXT" == "minor" || "$NEXT" == "major" ]]; then
     VERSION=$2
+else
+    # we assume it's init or x.x.x
+    if [[ $# == 2 ]]; then
+        (>&2 echo "can't increment from $2 to $1")
+        exit 1
+    fi
+    VERSION=$1
 fi
+
 
 PATTERN="^\(.*\)\.\(.*\)\.\(.*\)"
 
